remote_theme             : "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin    : "default"

# Site Settings
locale                   : "en-US"
title                    : "Ramblings and tidbits"
title_separator          : "-"
subtitle                 : "PowerShell, Linux, and everything in between"
name                     : "Peppe Kerstens"
description              : "Ramblings of any and all things that keep me awake at night or busy at day"
url                      : "https://peppekerstens.github.io"
repository               : "peppekerstens/peppekerstens.github.io"
breadcrumbs              : true
words_per_minute         : 200
enable_copy_code_button  : true
search                   : true
atom_feed:
  path                   :
  hide                   :

# Site Author
author:
  name             : "Peppe Kerstens"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Just another IT guy, husband, dad, feeling the aging"
  location         : "Netherlands"
  email            :
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peppekerstens"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peppekerstens"


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - node_modules
  - tmp
  - /docs
  - /test
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/


paginate: 5
paginate_path: /page:num/


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
